### ISSUE TITLE
Support for fully-qualified domain names

### ISSUE THREAD

**Issue by Chaz6** [Edu4rdSHL/rusolver#10]
At present, no results are returned when supplying a fully-qualified domain name:-

```
$ echo www.example.com. | rusolver

$ echo www.example.com | rusolver
www.example.com
```

**Comment by Edu4rdSHL** [comment]
Rusolver use FQDNs [by default](https://github.com/Edu4rdSHL/rusolver/blob/50b0e6bcdc11bead1c5230dbb21ca29055eb8aba/src/main.rs#L163-L164).

**Comment by Chaz6** [comment]
This means it is not possible to pass a proper fqdn to rusolver.

**Comment by Edu4rdSHL** [comment]
Right, it isn't gonna change.

**Comment by Edu4rdSHL** [comment]
The previous commit should fix it, please can you test?

**Comment by Chaz6** [comment]
Looks good to me!

```
$ echo www.example.com | rusolver
www.example.com
$ echo www.example.com. | rusolver
www.example.com.
```

Thank you 🤝
