### ISSUE TITLE
Fix the issue in windows!

### ISSUE THREAD

**Issue by Xeek3y** [Edu4rdSHL/rusolver#3]
Hello i tried the precompiled windows exe and the first time it worked as expected but on 2nd time it just gave me 2 subdomains live output and in the input subdomain text file there are at least 200 of subdomains and the tools now tells that only 2 subdomains are live which isn't the case in real and i also tried to compile the rust file on my machine but rust gave me few errors that i don't wanna fix(i guess a long fix requires). and tried downloading the exe file again and tried running as well but same it still gives me 2 subdomains only and 2-3 blank lines :(

**Comment by Edu4rdSHL** [comment]
Hello, I think you're having internet issues, can you try reducing the number of threads?

**Comment by Edu4rdSHL** [comment]
Closing because not answers from user.
