### ISSUE TITLE
No binary releases in 0.3.0 version

### ISSUE THREAD

**Issue by orhun** [Edu4rdSHL/rusolver#5]
Hey! I was about to update [rusolver-bin](https://aur.archlinux.org/packages/rusolver-bin) until I realized there isn't binary releases for `0.3.0`. Are you going to add them?

**Comment by Edu4rdSHL** [comment]
Hey! I forgot it, new binaries are available in the 0.4.0 release. https://github.com/Edu4rdSHL/rusolver/releases/tag/0.4.0
