### ISSUE TITLE
No binary releases in 0.5.1 version

### ISSUE THREAD

**Issue by mhmh55516** [Edu4rdSHL/rusolver#6]
Hey! I was about to update rusolver-bin until I realized there isn't linux binary release for 0.5.1. Are you going to add them?

**Comment by Edu4rdSHL** [comment]
Hello, there's `rusolver-linux`.

**Comment by mhmh55516** [comment]
i cant see it 
![image](https://user-images.githubusercontent.com/28407784/118526503-97f2e500-b740-11eb-8124-4bd97881fdfb.png)

**Comment by Edu4rdSHL** [comment]
It's weird, I can see it from the Android app but not from the desktop:

![image](https://user-images.githubusercontent.com/32582878/118548476-dfca3a00-b749-11eb-83a2-f749f49cc05b.png)

I have re-uploaded it and you should be able to download it.
