### ISSUE TITLE
Problem when adding ip list of resolvers 

### ISSUE THREAD

**Issue by MR-pentestGuy** [Edu4rdSHL/rusolver#7]
thread 'main' panicked at 'internal error: entered unreachable code: Error parsing the server 199.83.64.222 :53, only IPv4 are allowed. Error: invalid IP address syntax', src/main.rs:221:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thank you

**Comment by Edu4rdSHL** [comment]
Add only the IP, not the port.
