### ISSUE TITLE
could you add a new function for manually inputting the resolver list

### ISSUE THREAD

**Issue by blackcodersec** [Edu4rdSHL/rusolver#8]
could you add a new function for manually inputting the resolver list

**Comment by Edu4rdSHL** [comment]
Hello, the option `-r/--resolvers` option works for it, just put your DNS ips in a file and use that option.

**Comment by blackcodersec** [comment]
![image](https://user-images.githubusercontent.com/72689232/142649528-8e2a121b-cd76-4b33-b85a-28e809607c37.png)
 not working

**Comment by Edu4rdSHL** [comment]
Are you using the latest version of the tool? https://github.com/Edu4rdSHL/rusolver/tree/0.7.0, use `rusolver -V` to check the version.

**Comment by blackcodersec** [comment]
Ohh sorry sorry. I installed from `cargo install rusolver` command. Thanks. and sorry for this issue.

**Comment by blackcodersec** [comment]
![image](https://user-images.githubusercontent.com/72689232/142651759-7861b40f-2408-497a-870c-af1bc1abfbe7.png)

**Comment by Edu4rdSHL** [comment]
You have an empty line in the file. I will add a better error message for it soon. Please check that there aren't empty lines and the IPs are valid IPv4

**Comment by blackcodersec** [comment]
ohh. it was the first line empty, that's why. Ok done.
